import { Inter } from "next/font/google";
import "./output.css";

const inter = Inter({
  variable: "--font-Inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Untitled Research App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-ice-blue font-kaisei">
        {children}
      </body>
    </html>
  );
}